# Timeout in seconds that Limine will use before automatically booting.
timeout: 3

# The entry name that will be displayed in the boot menu.
/GooseOS Rewrite v0.1
    # We use the Limine boot protocol to load our kernel!
    protocol: limine
    path: boot():/boot/kernel.elf